language: go
go:
- master
branches:
  only:
  - master
install:
- go get github.com/spf13/hugo
script:
- hugo
deploy:
  local_dir: public
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_24638d97cf1a_key -iv $encrypted_24638d97cf1a_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
