language: go
addons:
  ssh_known_hosts: 47.75.56.14
go:
- master
branches:
  only:
  - master
install:
- go get github.com/spf13/hugo
script:
- hugo
before_install:
- openssl aes-256-cbc -K $encrypted_24638d97cf1a_key -iv $encrypted_24638d97cf1a_iv
  -in deploy_rsa.enc -out ~\/.ssh/deploy_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
- ssh root@47.75.56.14 StrictHostKeyChecking=no 'cd /www/amorist/ && git checkout
  gh-pages && git pull'
