baseURL = "https://amorist.io/"
languageCode = "en-us"
title = "Amor"
theme = "coder-portfolio"

paginate = 20

pygmentsUseClasses = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

googleAnalytics = "UA-76504285-9"

[params]
    author = "amor"
    info = "a cute boy"
    description = "amor's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "https://avatars2.githubusercontent.com/u/14037268?s=460&v=4"

    # footercontent = "Enter a text here." # Add footer content
    # fixedbarContent = "Do you want to know me more private?→" # Add fixedbar content
    # fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    snsShare = false # new add

    # thumbnail = "images/tn.png" # default sns thumbnail
[params.gitalk]
    enable = true
    clientID = "ba080f7cb1a46e7901fe"
    clientSecret = "990d1b1576febce451a89414d30a15e555f89621"
    repo = "amorist"
    owner =  "amorist"
    admin = "amorist"
    distractionFreeMode = false 

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/amorist"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/amor90s"
[[params.social]]
    name = "Instagram"
    weight = 3
    url = "https://www.instagram.com/amor.zhang"
[[params.social]]
    name = "Sponsors"
    weight = 4
    url = "https://github.com/sponsors/amorist"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "Photos"
    weight = 2
    url  = "photos"
[[menu.main]]
    name = "Project"
    weight = 3
    url = "project"
[[menu.main]]
    name = "About"
    weight = 4
    url = "about"